# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    # Add assignees
    assignees:
      - "clouddrove-ci"
    # Add reviewer
    reviewers:
      - "approvers"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "_example/aurora-mysql" # Location of package manifests
    schedule:
      interval: "weekly"
    # Add assignees
    assignees:
      - "clouddrove-ci"
    # Add reviewer
    reviewers:
      - "approvers"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "_example/aurora-mysql-serverless" # Location of package manifests
    schedule:
      interval: "weekly"
   # Add assignees
    assignees:
      - "clouddrove-ci"
    # Add reviewer
    reviewers:
      - "approvers"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "_example/aurora-postgre" # Location of package manifests
    schedule:
      interval: "weekly"
    # Add assignees
    assignees:
      - "clouddrove-ci"
    # Add reviewer
    reviewers:
      - "approvers"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "_example/aurora-postgre-serverless" # Location of package manifests
    schedule:
      interval: "weekly"
    # Add assignees
    assignees:
      - "clouddrove-ci"
    # Add reviewer
    reviewers:
      - "approvers"