---
name: Auto merge
on:
  pull_request:
jobs:
  auto-merge:
    uses: clouddrove/github-shared-workflows/.github/workflows/auto_merge.yml@1.2.0
    secrets:
      GITHUB: ${{ secrets.GITHUB }}
    with:
      tfcheck: 'tf-checks-aaurora-postgres-serverless-example / Check code format'
...
