name: 'Terraform GitHub Actions'
on:
  pull_request:
    branches:
      - master
jobs:
  fmt:
    name: 'terraform fmt'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2.3.4

      - name: 'Terraform Format'
        uses: 'clouddrove/github-actions@v7.0'
        with:
          actions_subcommand: 'fmt'

  aurora-mysql:
    name: 'aurora-mysql'
    needs: fmt
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2.3.4

      - name: 'Configure AWS Credentials'
        uses: clouddrove/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.TEST_AWS_ACCESS_SECRET_KEY }}
          aws-region: us-east-2

      - name: 'Terraform init for aurora-mysql '
        uses: 'clouddrove/github-actions@v7.0'
        with:
          actions_subcommand: 'init'
          tf_actions_working_dir: ./_example/aurora-mysql

      - name: 'Terraform validate for aurora-mysql '
        uses: 'clouddrove/github-actions@v7.0'
        with:
          actions_subcommand: 'validate'
          tf_actions_working_dir: ./_example/aurora-mysql

      - name: 'Terraform plan for aurora-mysql'
        uses: 'clouddrove/github-actions@v7.0'
        with:
          actions_subcommand: 'plan'
          tf_actions_working_dir: ./_example/aurora-mysql

  aurora-mysql-serverless:
    name: 'aurrora-mysql-serverless'
    needs: fmt
    runs-on: ubuntu-latest
    steps:

      - name: 'Checkout'
        uses: actions/checkout@v2.3.4

      - name: 'Configure AWS Credentials'
        uses: clouddrove/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.TEST_AWS_ACCESS_SECRET_KEY }}
          aws-region: us-east-2

      - name: 'Terraform init for  aurora-mysql-serverless'
        uses: 'clouddrove/github-actions@v7.0'
        with:
          actions_subcommand: 'init'
          tf_actions_working_dir: ./_example/aurora-mysql-serverless

      - name: 'Terraform validate for  aurora-mysql-serverless'
        uses: 'clouddrove/github-actions@v7.0'
        with:
          actions_subcommand: 'validate'
          tf_actions_working_dir: ./_example/aurora-mysql-serverless

      - name: 'Terraform plan for generate aurora-mysql-serverless'
        uses: 'clouddrove/github-actions@v7.0'
        with:
          actions_subcommand: 'plan'
          tf_actions_working_dir: ./_example/aurora-mysql-serverless

  aurora-postgre:
    name: 'aurora-postgre'
    needs: fmt
    runs-on: ubuntu-latest
    steps:

      - name: 'Checkout'
        uses: actions/checkout@v2.3.4

      - name: 'Configure AWS Credentials'
        uses: clouddrove/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.TEST_AWS_ACCESS_SECRET_KEY }}
          aws-region: us-east-2

      - name: 'Terraform init for aurora-postgre'
        uses: 'clouddrove/github-actions@v7.0'
        with:
          actions_subcommand: 'init'
          tf_actions_working_dir: ./_example/aurora-postgre

      - name: 'Terraform validate for  aurora-postgre'
        uses: 'clouddrove/github-actions@v7.0'
        with:
          actions_subcommand: 'validate'
          tf_actions_working_dir: ./_example/aurora-postgre

      - name: 'Terraform plan for  aurora-postgre'
        uses: 'clouddrove/github-actions@v7.0'
        with:
          actions_subcommand: 'plan'
          tf_actions_working_dir: ./_example/aurora-postgre

  aurora-postgre-serverless:
    name: 'aurora-postgre-serverless'
    needs: fmt
    runs-on: ubuntu-latest
    steps:

      - name: 'Checkout'
        uses: actions/checkout@v2.3.4

      - name: 'Configure AWS Credentials'
        uses: clouddrove/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.TEST_AWS_ACCESS_SECRET_KEY }}
          aws-region: us-east-2

      - name: 'Terraform init for generate certificate aurora-postgre-serverless'
        uses: 'clouddrove/github-actions@v7.0'
        with:
          actions_subcommand: 'init'
          tf_actions_working_dir: ./_example/aurora-postgre-serverless

      - name: 'Terraform validate for aurora-postgre-serverless'
        uses: 'clouddrove/github-actions@v7.0'
        with:
          actions_subcommand: 'validate'
          tf_actions_working_dir: ./_example/aurora-postgre-serverless

      - name: 'Terraform plan for aurora-postgre-serverless'
        uses: 'clouddrove/github-actions@v7.0'
        with:
          actions_subcommand: 'plan'
          tf_actions_working_dir: ./_example/aurora-postgre-serverless

  pre-commit:
    name: 'Pre-Commit'
    needs:
      - fmt
      - aurora-mysql
      - aurora-mysql-serverless
      - aurora-postgre
      - aurora-postgre-serverless
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2.3.4

      - name: 'Install Tflint'
        run: |
          curl https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: 'Pre-Commit 🔎'
        uses: pre-commit/action@v2.0.3
        continue-on-error: true

      - name: 'Slack Notification'
        uses: clouddrove/action-slack@v2
        with:
          status: ${{ job.status }}
          fields: repo,author
          author_name: 'CloudDrove'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # required
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_TERRAFORM }} # required
        if: always()
